/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;
 
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class aboutTrek extends javax.swing.JFrame {

    /**
     * Creates new form aboutTrek
     */
    public aboutTrek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        testField = new javax.swing.JTextField();
        testButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        showTrek = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testFieldActionPerformed(evt);
            }
        });
        jPanel9.add(testField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 30));

        testButton.setText("ENTER");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });
        jPanel9.add(testButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name of Trek"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setText("Search For Trek to continue :");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        showTrek.setText("SHOW TREKS");
        showTrek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTrekActionPerformed(evt);
            }
        });
        jPanel9.add(showTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, 30));

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel9.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, 30));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 340, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 10, 1000, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testFieldActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed

        String trekName = testField.getText();

        int a = TrekDataFetch(trekName);
        if(a == 1){
            addImageLabel(trekName);
        }
    }//GEN-LAST:event_testButtonActionPerformed

    private void showTrekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTrekActionPerformed
        // TODO add your handling code here:
        Connection con = DatabaseConnection.connect();
        String tableQuery = "SELECT name from trek_data";
        try {
            Statement statement = con.createStatement();
            ResultSet result = statement.executeQuery(tableQuery);

            DefaultTableModel model =  (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(result.next())
            {
                String name = result.getString("name");
                Object[] rowData = {name};
                model.addRow(rowData);
            }
            statement.close();

        } catch (SQLException ex) {
            Logger.getLogger(joinatrek.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            DatabaseConnection.disconnect();
        }

    }//GEN-LAST:event_showTrekActionPerformed
      private int TrekDataFetch(String name){
        try {
            
            Connection con = DatabaseConnection.connect();
            String query = "SELECT * from trek_data where name = ?";
            PreparedStatement statement = con.prepareStatement(query);
            
            statement.setString(1, name);
            ResultSet resultSet = statement.executeQuery();
            
            try {
                if(resultSet.next())
                {

                    info = resultSet.getString("info");

                    resultSet.close();
                    statement.close();
                    con.close();
                    return 1;
                } else {
                    JOptionPane.showMessageDialog(this, "Trek Name not Found");
                    resultSet.close();
                    statement.close();
                    con.close();
                    return 0;
                }
            } catch (SQLException ex) {
                Logger.getLogger(joinatrek.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch(SQLException ex){
            
        }
        return 0;
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        aboutTrek.this.dispose();
        dashboard_v2 db = new dashboard_v2();
        db.setLocationRelativeTo(null);
        db.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    private void addImageLabel(String trekName){
        int x = TrekCode.x_label;
        int y = TrekCode.y_label;
        int height = TrekCode.height_label;
        int width = TrekCode.width_label;
        TrekCode trekcode = new TrekCode();
        ImageIcon imageIcon = getImageFromDatabase(trekName);
        
        ImageLabel = new javax.swing.JLabel(imageIcon);
        ImagePanel = new javax.swing.JPanel();
       
        ButtonToInfo = new javax.swing.JButton();
        TrekLabel = new javax.swing.JLabel();
        ImageInPanel = new javax.swing.JPanel();
        
        ImageInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
       
        
        ImagePanel.setBackground(new java.awt.Color(205, 205, 205));
        ImagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ImagePanel.setMaximumSize(new java.awt.Dimension(270, 240));
        ImagePanel.setMinimumSize(new java.awt.Dimension(270, 240));
        ImagePanel.setRequestFocusEnabled(false);
        
        
        
        getContentPane().add(ImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y , width, height ));
        
        TrekLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TrekLabel.setText(trekName);
        TrekLabel.setSize(new Dimension(width,height));
        ImagePanel.add(TrekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 24));
        
        ImageInPanel.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 140));
        
        ImagePanel.add(ImageInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 140) );
        
        
        
        ButtonToInfo.setText("INFO");
        ButtonToInfo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                infoButtonActionPerformed(e);
            }
            private void infoButtonActionPerformed(ActionEvent evt){
                TrekInfo trekinfo = new TrekInfo();
                
                trekinfo.setTrekName(trekName);
                trekinfo.setTrekArea(info);
                trekinfo.setLocationRelativeTo(null);
                trekinfo.setVisible(true);
            }
        });
        
        
        ImagePanel.add(ButtonToInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        
        TrekCode.x_label = trekcode.X_Cordinates(x);
        TrekCode.y_label = trekcode.Y_Cordinates(x, y);
        ImagePanel.revalidate();
        ImagePanel.repaint();
    }
    
    
    private ImageIcon getImageFromDatabase(String trekName) {
    try {
        Connection con = DatabaseConnection.connect();
        String selectQuery = "SELECT image FROM trek_data WHERE name = ?";
        try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
            statement.setString(1, trekName);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Blob imageBlob = resultSet.getBlob("image");
                    byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                    ImageIcon imageIcon = new ImageIcon(imageBytes);
                    return imageIcon;
                }
            }
        }
    } catch (SQLException ex) {
    } finally {
        DatabaseConnection.disconnect();
    }
    return null;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutTrek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutTrek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutTrek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutTrek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutTrek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showTrek;
    private javax.swing.JButton testButton;
    private javax.swing.JTextField testField;
    // End of variables declaration//GEN-END:variables
    private String info;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JButton ButtonToInfo;
    private javax.swing.JLabel ImageLabel;
   
    private javax.swing.JLabel TrekLabel;
    private javax.swing.JPanel ImageInPanel;
    private javax.swing.JPanel TrekInfoPanel;
    private Component component;
    private String trekName2;
}
