/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
public class addGear extends javax.swing.JFrame {

    /**
     * Creates new form addGear
     */
    public addGear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblcreate_trek = new javax.swing.JLabel();
        jlabitinary = new javax.swing.JLabel();
        jlbheight = new javax.swing.JLabel();
        jlabeltransportation = new javax.swing.JLabel();
        jlbinclusion = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        Feature3Field = new javax.swing.JTextField();
        Feature2Field = new javax.swing.JTextField();
        imageField = new javax.swing.JTextField();
        jlbtrekname = new javax.swing.JLabel();
        jlblocation1 = new javax.swing.JLabel();
        gearItem = new javax.swing.JTextField();
        feature1Field = new javax.swing.JTextField();
        confirmbutton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        attachButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblcreate_trek.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLblcreate_trek.setForeground(new java.awt.Color(255, 255, 255));
        jLblcreate_trek.setText("ADD GEAR");
        jPanel1.add(jLblcreate_trek, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 33, 246, 52));

        jlabitinary.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlabitinary.setForeground(new java.awt.Color(255, 255, 255));
        jlabitinary.setText("PRICE");
        jPanel1.add(jlabitinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 182, 47));

        jlbheight.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbheight.setForeground(new java.awt.Color(255, 255, 255));
        jlbheight.setText("Feature2");
        jPanel1.add(jlbheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 182, 47));

        jlabeltransportation.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlabeltransportation.setForeground(new java.awt.Color(255, 255, 255));
        jlabeltransportation.setText("Feature3");
        jPanel1.add(jlabeltransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 182, 47));

        jlbinclusion.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbinclusion.setForeground(new java.awt.Color(255, 255, 255));
        jlbinclusion.setText("Upload Image");
        jPanel1.add(jlbinclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 182, 47));

        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 384, 228, 47));

        Feature3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feature3FieldActionPerformed(evt);
            }
        });
        jPanel1.add(Feature3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 312, 228, 47));

        Feature2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feature2FieldActionPerformed(evt);
            }
        });
        jPanel1.add(Feature2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 238, 228, 47));

        imageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageFieldActionPerformed(evt);
            }
        });
        jPanel1.add(imageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 456, 228, 49));

        jlbtrekname.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbtrekname.setForeground(new java.awt.Color(255, 255, 255));
        jlbtrekname.setText("Name of item");
        jPanel1.add(jlbtrekname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 182, 47));

        jlblocation1.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlblocation1.setForeground(new java.awt.Color(255, 255, 255));
        jlblocation1.setText("Feature1");
        jPanel1.add(jlblocation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 47));

        gearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gearItemActionPerformed(evt);
            }
        });
        jPanel1.add(gearItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 228, 47));

        feature1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature1FieldActionPerformed(evt);
            }
        });
        jPanel1.add(feature1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 228, 47));

        confirmbutton.setBackground(new java.awt.Color(102, 102, 102));
        confirmbutton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        confirmbutton.setForeground(new java.awt.Color(255, 255, 255));
        confirmbutton.setText("CONFIRM");
        confirmbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 120, 40));

        homeButton.setBackground(new java.awt.Color(102, 102, 102));
        homeButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 120, 40));

        attachButton.setBackground(new java.awt.Color(102, 102, 102));
        attachButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        attachButton.setForeground(new java.awt.Color(255, 255, 255));
        attachButton.setText("ADD IMAGE");
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        jPanel1.add(attachButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed

    private void Feature3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feature3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Feature3FieldActionPerformed

    private void Feature2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feature2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Feature2FieldActionPerformed

    private void imageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageFieldActionPerformed

    private void gearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gearItemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_gearItemActionPerformed

    private void feature1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feature1FieldActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        // TODO add your handling code here:
        String enteredName = gearItem.getText();
        String enteredfeature1 = feature1Field.getText();
        String enteredfeature2 = Feature2Field.getText();
        String enteredfeature3 = Feature3Field.getText();
        int enteredPrice = Integer.parseInt(PriceField.getText());
        
        

     

     
        Connection con = DatabaseConnection.connect();
        String trekQuery = "INSERT into gear_data(name, feature1, feature2, feature3, price,image) VALUES(?,?,?,?,?,?)";

        try(PreparedStatement statement = con.prepareStatement(trekQuery)){
            statement.setString(1, enteredName);
            statement.setString(2, enteredfeature1);
            statement.setString(3, enteredfeature2);
            statement.setString(4, enteredfeature3);
            statement.setInt(5, enteredPrice);
            
            

            FileInputStream fis;
            try {
                fis = new FileInputStream(filename);
                statement.setBinaryStream(6, fis);
            } catch (FileNotFoundException ex) {
                
            }

            statement.executeUpdate();
        }
        catch(SQLException ex){System.out.print(ex);}
        finally{
            DatabaseConnection.disconnect();
        }

        

    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        addGear.this.dispose();
        AdminDashboard ad = new AdminDashboard();
        
        ad.setLocationRelativeTo(null);
        ad.setVisible(true);

    }//GEN-LAST:event_homeButtonActionPerformed

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        TrekData.setFilename(filename);
        
        
    }//GEN-LAST:event_attachButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addGear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addGear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addGear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addGear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addGear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Feature2Field;
    private javax.swing.JTextField Feature3Field;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton attachButton;
    private javax.swing.JButton confirmbutton;
    private javax.swing.JTextField feature1Field;
    private javax.swing.JTextField gearItem;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField imageField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblcreate_trek;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabeltransportation;
    private javax.swing.JLabel jlabitinary;
    private javax.swing.JLabel jlbheight;
    private javax.swing.JLabel jlbinclusion;
    private javax.swing.JLabel jlblocation1;
    private javax.swing.JLabel jlbtrekname;
    // End of variables declaration//GEN-END:variables
    private String filename;
    
}
