/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author main
 */
package trekmosaic;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class createtrek extends javax.swing.JFrame {

    /**
     * Creates new form createtrek
     */
    public createtrek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblcreate_trek = new javax.swing.JLabel();
        jlabitinary = new javax.swing.JLabel();
        jlbheight = new javax.swing.JLabel();
        jlabeltransportation = new javax.swing.JLabel();
        jlabelinfo = new javax.swing.JLabel();
        jlbinclusion = new javax.swing.JLabel();
        itinaryField = new javax.swing.JTextField();
        transportationNameField = new javax.swing.JTextField();
        heightNameField = new javax.swing.JTextField();
        inclusionsNameField = new javax.swing.JTextField();
        infoNameField = new javax.swing.JTextField();
        jlbtrekname = new javax.swing.JLabel();
        jlbprice = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jlblocation1 = new javax.swing.JLabel();
        trekNameField = new javax.swing.JTextField();
        locNameField = new javax.swing.JTextField();
        confirmbutton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        attachButton = new javax.swing.JButton();
        attachtextButton = new javax.swing.JButton();
        infoAttach = new javax.swing.JButton();
        addGearButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        jLblcreate_trek.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLblcreate_trek.setForeground(new java.awt.Color(255, 255, 255));
        jLblcreate_trek.setText("Create Trek");
        jLblcreate_trek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLblcreate_trek);
        jLblcreate_trek.setBounds(20, 10, 220, 60);

        jlabitinary.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlabitinary.setForeground(new java.awt.Color(255, 255, 255));
        jlabitinary.setText("Short Itinary");
        jPanel1.add(jlabitinary);
        jlabitinary.setBounds(510, 90, 150, 40);

        jlbheight.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlbheight.setForeground(new java.awt.Color(255, 255, 255));
        jlbheight.setText("Height");
        jPanel1.add(jlbheight);
        jlbheight.setBounds(110, 230, 80, 47);

        jlabeltransportation.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlabeltransportation.setForeground(new java.awt.Color(255, 255, 255));
        jlabeltransportation.setText("Transportation");
        jPanel1.add(jlabeltransportation);
        jlabeltransportation.setBounds(20, 300, 182, 47);

        jlabelinfo.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlabelinfo.setForeground(new java.awt.Color(255, 255, 255));
        jlabelinfo.setText("Information of trek ");
        jPanel1.add(jlabelinfo);
        jlabelinfo.setBounds(450, 280, 260, 80);

        jlbinclusion.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlbinclusion.setForeground(new java.awt.Color(255, 255, 255));
        jlbinclusion.setText("Inclusions");
        jPanel1.add(jlbinclusion);
        jlbinclusion.setBounds(540, 160, 120, 47);

        itinaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itinaryFieldActionPerformed(evt);
            }
        });
        jPanel1.add(itinaryField);
        itinaryField.setBounds(660, 90, 228, 47);

        transportationNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportationNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(transportationNameField);
        transportationNameField.setBounds(190, 300, 228, 47);

        heightNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(heightNameField);
        heightNameField.setBounds(190, 230, 228, 47);

        inclusionsNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclusionsNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(inclusionsNameField);
        inclusionsNameField.setBounds(660, 160, 228, 49);

        infoNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(infoNameField);
        infoNameField.setBounds(660, 300, 228, 47);

        jlbtrekname.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlbtrekname.setForeground(new java.awt.Color(255, 255, 255));
        jlbtrekname.setText("Name of trek ");
        jPanel1.add(jlbtrekname);
        jlbtrekname.setBounds(50, 90, 150, 47);

        jlbprice.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlbprice.setForeground(new java.awt.Color(255, 255, 255));
        jlbprice.setText("Price");
        jPanel1.add(jlbprice);
        jlbprice.setBounds(590, 230, 70, 47);

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        jPanel1.add(priceField);
        priceField.setBounds(660, 230, 228, 47);

        jlblocation1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jlblocation1.setForeground(new java.awt.Color(255, 255, 255));
        jlblocation1.setText("Location");
        jPanel1.add(jlblocation1);
        jlblocation1.setBounds(90, 160, 100, 47);

        trekNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trekNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(trekNameField);
        trekNameField.setBounds(190, 90, 228, 47);

        locNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(locNameField);
        locNameField.setBounds(190, 160, 228, 47);

        confirmbutton.setBackground(new java.awt.Color(102, 102, 102));
        confirmbutton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        confirmbutton.setForeground(new java.awt.Color(255, 255, 255));
        confirmbutton.setText("CONFIRM TREK ");
        confirmbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmbutton);
        confirmbutton.setBounds(430, 460, 200, 40);

        homeButton.setBackground(new java.awt.Color(102, 102, 102));
        homeButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(870, 570, 120, 40);

        attachButton.setBackground(new java.awt.Color(204, 204, 204));
        attachButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        attachButton.setText("UPLOAD PHOTO ");
        attachButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        jPanel1.add(attachButton);
        attachButton.setBounds(550, 390, 150, 40);

        attachtextButton.setBackground(new java.awt.Color(204, 204, 204));
        attachtextButton.setText("ATTACH");
        attachtextButton.setActionCommand("");
        attachtextButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        attachtextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachtextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(attachtextButton);
        attachtextButton.setBounds(890, 90, 90, 20);

        infoAttach.setBackground(new java.awt.Color(204, 204, 204));
        infoAttach.setText("ATTACH");
        infoAttach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        infoAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAttachActionPerformed(evt);
            }
        });
        jPanel1.add(infoAttach);
        infoAttach.setBounds(890, 300, 100, 20);

        addGearButton.setText("ADD GEAR");
        addGearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addGearButton);
        addGearButton.setBounds(700, 570, 110, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attach Info text file");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(890, 320, 130, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attach Itenary text file");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(890, 110, 130, 16);

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trek Photo to Display :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 390, 260, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, 0, 1080, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transportationNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportationNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportationNameFieldActionPerformed

    private void heightNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightNameFieldActionPerformed

    private void itinaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itinaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itinaryFieldActionPerformed

    private void trekNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trekNameFieldActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_trekNameFieldActionPerformed

    private void locNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locNameFieldActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        createtrek.this.dispose();
        dashboard_v2 db = new dashboard_v2();
        db.setLocationRelativeTo(null);
        db.setVisible(true);
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        // TODO add your handling code here:
      String enteredName = trekNameField.getText(); 
      String enteredLocation = locNameField.getText();
      String enteredHeight = heightNameField.getText();
      String enteredTransportationName = transportationNameField.getText();
      String enteredItinary = itinaryField.getText();
      String enteredInclusionsName = inclusionsNameField.getText();
      String enteredInfoName = infoNameField.getText();
      String enteredPrice = priceField.getText();
      
      
      TrekData.setTrekname(enteredName);
      TrekData.setLocName(enteredLocation);
      TrekData.setHeightName(enteredHeight);
      TrekData.setTransportationName(enteredTransportationName);
      TrekData.setItinary(enteredItinary);
      TrekData.setinclusionsName(enteredInclusionsName);
      TrekData.setinfoName(enteredInfoName);
      TrekData.setPrice(enteredPrice);
      
      
      String trekName = TrekData.getTrekname();
      String locName = TrekData.getLocName();
      String heightName = TrekData.getHeightName();
      String transportationName = TrekData.getTransportationName();
      String itinary = contents.toString();
      String inclusionsName = TrekData.getInclusionsName();
      String infoName = TrekData.getinfoName();
      String price = TrekData.getPrice();
      String filepath = TrekData.getFilename();
      
      Connection con = DatabaseConnection.connect();
      String trekQuery = "INSERT into trek_data(name, location, height, transport, short_itinerary, inclusions, new_info, price, image ) VALUES(?,?,?,?,?,?,?,?,?)";
      
      try(PreparedStatement statement = con.prepareStatement(trekQuery)){
         statement.setString(1, trekName);
         statement.setString(2, locName);
         statement.setString(3, heightName);
         statement.setString(4, transportationName);
         statement.setString(5, itinary);
         statement.setString(6, inclusionsName);
         statement.setString(7, infoName);
         statement.setString(8, price);
         
         FileInputStream fis;
          try {
              fis = new FileInputStream(filepath);
              statement.setBinaryStream(9, fis);
          } catch (FileNotFoundException ex) {
              Logger.getLogger(createtrek.class.getName()).log(Level.SEVERE, null, ex);
          }
         
         statement.executeUpdate();
      } 
      catch(SQLException ex){System.out.print(ex);}
        finally{
            DatabaseConnection.disconnect();
        }
        
    
    
      
      DisplayCreateTrek display = new DisplayCreateTrek();
      DisplayCreateTrek.trekNameDisplayLabel.setText("Name of Trek : " + trekName);
      DisplayCreateTrek.locNameDisplayLabel.setText("Location of trek : " + locName );
      DisplayCreateTrek.heightNameDisplayLabel.setText("Height : " + heightName);
      DisplayCreateTrek.transportationNameDisplayLabel.setText("Transportation : " + transportationName);
      DisplayCreateTrek.itinaryDisplayLabel.setText("Short Itiary : " + itinary);
      DisplayCreateTrek.inclusionsNameDisplayLabel.setText("Inclusions : " + inclusionsName);
      DisplayCreateTrek.infoNameDisplayLabel.setText("Information about Trek : " + infoName);
      DisplayCreateTrek.priceDisplayLabel.setText("Price : " + price);
      
      display.setLocationRelativeTo(null);
      display.setVisible(true);
      
      
      
      
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void inclusionsNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclusionsNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inclusionsNameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        TrekData.setFilename(filename);
    }//GEN-LAST:event_attachButtonActionPerformed

    private void attachtextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachtextButtonActionPerformed
      
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            
            try {
                File selectedFile = fileChooser.getSelectedFile();
                String filepath = selectedFile.getAbsolutePath();
                
                contents = new StringBuilder();
                BufferedReader br = new BufferedReader(new FileReader(filepath));
                String line;
                while((line = br.readLine()) != null){
                    contents.append(line).append("\n");
                }
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(createtrek.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
        String s = contents.toString();
      itinaryField.setText(s);
            
        
    }//GEN-LAST:event_attachtextButtonActionPerformed

    private void infoAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAttachActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            
            try {
                File selectedFile = fileChooser.getSelectedFile();
                String filepath = selectedFile.getAbsolutePath();
                
                contents = new StringBuilder();
                BufferedReader br = new BufferedReader(new FileReader(filepath));
                String line;
                while((line = br.readLine()) != null){
                    contents.append(line).append("\n");
                }
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(createtrek.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
        String s = contents.toString();
      infoNameField.setText(s);
    }//GEN-LAST:event_infoAttachActionPerformed

    private void addGearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGearButtonActionPerformed
        // TODO add your handling code here:
        addGear g = new addGear();
        createtrek.this.dispose();
        g.setLocationRelativeTo(null);
        g.setVisible(true);
    }//GEN-LAST:event_addGearButtonActionPerformed

    private void infoNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGearButton;
    private javax.swing.JButton attachButton;
    private javax.swing.JButton attachtextButton;
    private javax.swing.JButton confirmbutton;
    private javax.swing.JTextField heightNameField;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField inclusionsNameField;
    private javax.swing.JButton infoAttach;
    private javax.swing.JTextField infoNameField;
    private javax.swing.JTextField itinaryField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblcreate_trek;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabelinfo;
    private javax.swing.JLabel jlabeltransportation;
    private javax.swing.JLabel jlabitinary;
    private javax.swing.JLabel jlbheight;
    private javax.swing.JLabel jlbinclusion;
    private javax.swing.JLabel jlblocation1;
    private javax.swing.JLabel jlbprice;
    private javax.swing.JLabel jlbtrekname;
    private javax.swing.JTextField locNameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField transportationNameField;
    private javax.swing.JTextField trekNameField;
    // End of variables declaration//GEN-END:variables
    private StringBuilder contents;
}

