/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
/**
 *
 * @author ADMIN
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    public profile() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        locationLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        myprofiletext = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        instagramLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        verifybutton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        blankpfp = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JoinedTreks = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        addLINK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        createdTrek = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        textArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textArea1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textArea1);
        textArea1.setBounds(120, 320, 500, 80);

        locationLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        locationLabel.setText("location : ");
        jPanel1.add(locationLabel);
        locationLabel.setBounds(150, 180, 320, 30);

        jButton4.setText("home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1325, 682, 93, 23);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("HOME");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 580, 110, 40);

        myprofiletext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        myprofiletext.setText("MY PROFILE");
        jPanel1.add(myprofiletext);
        myprofiletext.setBounds(20, 30, 120, 50);

        ageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        ageLabel.setText("age : ");
        jPanel1.add(ageLabel);
        ageLabel.setBounds(150, 140, 310, 29);

        instagramLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        instagramLabel.setText("instagram : ");
        jPanel1.add(instagramLabel);
        instagramLabel.setBounds(100, 600, 430, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("About me : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 320, 72, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("Connect with me : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 570, 135, 22);

        verifybutton.setText("VERIFY PROFILE");
        verifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(verifybutton);
        verifybutton.setBounds(600, 110, 130, 30);

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 21)); // NOI18N
        nameLabel.setText("name :");
        nameLabel.setToolTipText("");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(150, 110, 230, 20);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blankpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/EMPTY_PFP.png"))); // NOI18N
        jPanel2.add(blankpfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 150));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 130, 130);

        uploadButton.setText("Upload Picture");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadButton);
        uploadButton.setBounds(20, 240, 120, 23);

        JoinedTreks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Joined Treks"
            }
        ));
        jScrollPane1.setViewportView(JoinedTreks);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 410, 130, 120);

        jButton2.setText("EDIT ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 370, 72, 23);

        addLINK.setText("ADD LINKS");
        addLINK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLINKActionPerformed(evt);
            }
        });
        jPanel1.add(addLINK);
        addLINK.setBounds(90, 640, 100, 20);

        createdTrek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "My Treks"
            }
        ));
        jScrollPane2.setViewportView(createdTrek);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(260, 410, 130, 120);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VERIFICATION STATUS : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 10, 320, 50);

        jButton3.setText("test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(650, 450, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 1080, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(UserData.upload == 1){
        Connection con = DatabaseConnection.connect();
        String query = "UPDATE user_data SET pfp = ? WHERE name = ?";
        
        try {
            PreparedStatement stm = con.prepareStatement(query);
            FileInputStream fis;
            try {
                fis = new FileInputStream(filename);
                stm.setBinaryStream(1, fis);
                stm.setString(2, Name);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
            }
            stm.executeUpdate();
            stm.close();
        } catch (SQLException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            DatabaseConnection.disconnect();
        }
        }
         
        
        
        
        
        profile.this.dispose();
        dashboard_v2 dashboard = new dashboard_v2();
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifybuttonActionPerformed
        // TODO add your handling code here:
        profile.this.dispose();
        Verification verify = new Verification();
        verify.setLocationRelativeTo(null);
        verify.setVisible(true);
    }//GEN-LAST:event_verifybuttonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        UserData.setFilename(filename);
       
        UserData.upload = 1;
        if(UserData.upload == 1)
        {        
        addImagePanel(filename);
        }
    }//GEN-LAST:event_uploadButtonActionPerformed
    
    
    
    
    private void addLINKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLINKActionPerformed
        // TODO add your handling code here:
        JDialog inputDialog = new JDialog();
        inputDialog.setLocationRelativeTo(null);
        inputDialog.setLayout(new FlowLayout());        
        javax.swing.JTextField linkTextField = new javax.swing.JTextField(20);
        javax.swing.JButton confirmButton = new javax.swing.JButton("Confirm");

        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the link from the text field
                String link = linkTextField.getText();

                
                instagramLabel.setText("Instagram: " + link);

                // Close the input dialog
                inputDialog.dispose();
            }
        });

        inputDialog.add(new javax.swing.JLabel("Enter Instagram Link:"));
        inputDialog.add(linkTextField);
        inputDialog.add(confirmButton);
        inputDialog.pack();
        inputDialog.setVisible(true);
    }//GEN-LAST:event_addLINKActionPerformed
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JDialog AboutMe = new JDialog();
        AboutMe.setLocationRelativeTo(null);
        AboutMe.setLayout(new FlowLayout());
        javax.swing.JTextField AboutmeField = new javax.swing.JTextField(50);
        javax.swing.JButton confirmButton2 = new javax.swing.JButton("Confirm");
        confirmButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String info = AboutmeField.getText();                
                textArea1.setText(info);               
                AboutMe.dispose();
            }
        });
        AboutMe.add(new javax.swing.JLabel("Enter About You :"));
        AboutMe.add(AboutmeField);
        AboutMe.add(confirmButton2);
        AboutMe.pack();
        AboutMe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdminVerification p = new AdminVerification();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    public void addImagePanel() {
        ImagePanel = new javax.swing.JPanel();
        ImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(ImagePanel);
        ImagePanel.setBounds(10, 90, 130, 130);

        ImageIcon icon = null;
        if (filename != null) {
            icon = new ImageIcon(filename);
        } else {
            icon = getImageFromDatabase(Name);
        }

        ImageLabel = new javax.swing.JLabel(icon);
        ImagePanel.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));



    }
        private void addImagePanel(String filename){
       ImagePanel = new javax.swing.JPanel();
       
       ImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
       jPanel1.add(ImagePanel);
       ImagePanel.setBounds(10, 90, 130, 130);
       
       ImageLabel = new javax.swing.JLabel();
       ImageIcon icon = new ImageIcon(filename);
       ImageLabel.setIcon(icon);
       ImagePanel.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));
       
    ImagePanel.revalidate();
    ImagePanel.repaint();
       
    }
    
    void setFilename(String txt){
        filename = txt;
    }
     void setTable(String name){
            DefaultTableModel model =  (DefaultTableModel)JoinedTreks.getModel();
            model.setRowCount(0);
            Object[] rowData = {name};
            model.addRow(rowData);
    }
     
     void setMyTrekTable(String name) {
            DefaultTableModel model = (DefaultTableModel)createdTrek.getModel();
            model.setRowCount(0);
            Object[] rowData = {name};
            model.addRow(rowData);
    }
    
    public void setName(String name){
        
        nameLabel.setText("name : " + name);
        Name = name;
    }
  
   
    public void setAge(int Age){
        ageLabel.setText(("Age : " + Age));
    }
    
    public void setLocation(String Location){
        locationLabel.setText(("Location : " + Location));
    }
    
    private ImageIcon getImageFromDatabase(String Name) {
    try {
        Connection con = DatabaseConnection.connect();
        String selectQuery = "SELECT pfp FROM user_data WHERE name = ?";
        try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
            statement.setString(1, Name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Blob imageBlob = resultSet.getBlob("image");
                    byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                    ImageIcon imageIcon = new ImageIcon(imageBytes);
                    return imageIcon;
                }
            }
        }
    } catch (SQLException ex) {
    } finally {
        DatabaseConnection.disconnect();
    }
    return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JoinedTreks;
    private javax.swing.JButton addLINK;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel blankpfp;
    private javax.swing.JTable createdTrek;
    private javax.swing.JLabel instagramLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel myprofiletext;
    private javax.swing.JLabel nameLabel;
    private java.awt.TextArea textArea1;
    private javax.swing.JButton uploadButton;
    private javax.swing.JButton verifybutton;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImageLabel;
    String Name;
    String filename;
}
