/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class verificationpopup extends javax.swing.JFrame {

    /**
     * Creates new form verificationpopup
     */
    public verificationpopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        documentPanel = new javax.swing.JPanel();
        pfpPanel = new javax.swing.JPanel();
        ageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        denyButton = new javax.swing.JButton();
        approveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        documentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(documentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 500, 300));

        pfpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pfpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 150, 130));

        ageLabel.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("AGE :");
        jPanel1.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 132, 465, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER DEATILS ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 444, 36));

        locationLabel.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(255, 255, 255));
        locationLabel.setText("LOCATION :");
        jPanel1.add(locationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 90, 484, 36));

        nameLabel.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("NAME :");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 48, 473, 36));

        jLabel30.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("DOCUMENT UPLOADED BY USER  :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, 444, 36));

        denyButton.setBackground(new java.awt.Color(255, 51, 51));
        denyButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        denyButton.setText("✘ DENY");
        denyButton.setToolTipText("");
        denyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(denyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 180, 40));

        approveButton.setBackground(new java.awt.Color(51, 255, 51));
        approveButton.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        approveButton.setText("✓ APPROVE ");
        approveButton.setToolTipText("");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(approveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 180, 40));

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void denyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyButtonActionPerformed
        // TODO add your handling code here:
        Connection con = DatabaseConnection.connect();
        String denyQuery = "UPDATE user_data SET verification_status = NULL WHERE name = ?";

        try {
            PreparedStatement stm2 = con.prepareStatement(denyQuery);
            stm2.setString(1, Name);
        } catch (SQLException ex) {
        }
        JOptionPane.showConfirmDialog(this, "This user has been verified");
    }//GEN-LAST:event_denyButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        Connection con = DatabaseConnection.connect();
        String query = "UPDATE user_data SET verification_status = 'Approved' WHERE name = ?";

        try {
            PreparedStatement stm = con.prepareStatement(query);
            stm.setString(1, Name);
            stm.executeUpdate();
        } catch (SQLException ex) {

        }

        JOptionPane.showConfirmDialog(this, "This user has been verified");
    }//GEN-LAST:event_approveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminVerification av = new AdminVerification();
        verificationpopup.this.dispose();
        av.setLocationRelativeTo(null);
        av.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    
    public void setName(String name) {
        nameLabel.setText("Name : " + name);
        Name = name;
        ImagePanel(name);
        DocumentPanel(name);

    }

    public void setLocation(String loc) {
        locationLabel.setText("Location : " + loc);
    }

    public void setAge(int age) {
        ageLabel.setText("Age :  " + age);
    }

    private void DocumentPanel(String Name) {
        ImageIcon imageIcon = getdocumentFromDatabase(Name);
        documentLabel = new javax.swing.JLabel();
        documentLabel.setIcon(imageIcon);
        documentPanel.add(documentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));
        documentPanel.revalidate();
        documentPanel.repaint();

    }

    private void ImagePanel(String Name) {
        ImageIcon imageIcon = getImageFromDatabase(Name);
        imageLabel = new javax.swing.JLabel(imageIcon);
        pfpPanel.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 130));
        pfpPanel.revalidate();
        pfpPanel.repaint();

    }

    private ImageIcon getdocumentFromDatabase(String Name) {
        try {
            Connection con = DatabaseConnection.connect();
            String selectQuery = "SELECT document FROM user_data WHERE name = ?";
            try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
                statement.setString(1, Name);
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        Blob imageBlob = resultSet.getBlob("document");
                        byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                        ImageIcon imageIcon = new ImageIcon(imageBytes);
                        return imageIcon;
                    }
                }
            }
        } catch (SQLException ex) {
        } finally {
            DatabaseConnection.disconnect();
        }
        return null;
    }
    
    private ImageIcon getImageFromDatabase(String Name) {
    try {
        Connection con = DatabaseConnection.connect();
        String selectQuery = "SELECT pfp FROM user_data WHERE name = ?";
        try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
            statement.setString(1, Name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Blob imageBlob = resultSet.getBlob("pfp");
                    byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                    ImageIcon imageIcon = new ImageIcon(imageBytes);
                    return imageIcon;
                }
            }
        }
    } catch (SQLException ex) {
    } finally {
        DatabaseConnection.disconnect();
    }
    return null;
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verificationpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verificationpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verificationpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verificationpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verificationpopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton approveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton denyButton;
    private javax.swing.JPanel documentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel pfpPanel;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel documentLabel;
    private javax.swing.JLabel imageLabel;
    String Name;
}
