/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
/**
 *
 * @author main
 */
public class Verification extends javax.swing.JFrame {

    /**
     * Creates new form Verification
     */
    public Verification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        verifyButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        uploaddoc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verfication ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 214, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Upload id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 108, 41));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 206, 47));

        verifyButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        verifyButton.setText("Verify");
        verifyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 100, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("                1-2 processing days to verify");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 460, 328, 31));

        homeButton.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        homeButton.setText("HOME");
        homeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 100, 30));

        uploaddoc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        uploaddoc.setText("Upload Documents");
        uploaddoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        uploaddoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploaddocActionPerformed(evt);
            }
        });
        jPanel1.add(uploaddoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1270, 730));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
       
        UserData.verify = 1;
        UserIndoData u = new UserIndoData();
        u.setPendingVerification(UserIndoData.getName());
        name = UserIndoData.getName();
       Connection con = DatabaseConnection.connect();
       if(filename != null){
       String query = "UPDATE user_data SET document = ? WHERE name = ?";
        
        try {
            PreparedStatement stm = con.prepareStatement(query);
            FileInputStream fis;
            try {
                fis = new FileInputStream(filename);
                stm.setBinaryStream(1, fis);
                stm.setString(2, name);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
            }
            stm.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            DatabaseConnection.disconnect();
        }
        if(filename != null){
        updateVerificationStatus(name);
       }
       }        
       else
       {
           JOptionPane.showMessageDialog(this, "Document not found");
       }
       
       JOptionPane.showConfirmDialog(this, "Image sent for verification to admin");
    }//GEN-LAST:event_verifyButtonActionPerformed
    private void updateVerificationStatus(String name){
        Connection con = DatabaseConnection.connect();
        String verifyquery = "UPDATE user_data SET verification_status = ? WHERE name = ?";
        String update = "Pending Verification";
        try {
            PreparedStatement stm2 = con.prepareStatement(verifyquery);
            stm2.setString(1, update);
            stm2.setString(2, name);
            stm2.executeUpdate();
        } catch (SQLException ex) {
            
        } finally {
            DatabaseConnection.disconnect();
        }
      
        
    }   
    
        
    
    
    
    
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
      
        Verification.this.dispose();
        dashboard_v2 db = new dashboard_v2();
        db.setLocationRelativeTo(null);
        db.setVisible(true);
       
        
            
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void uploaddocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploaddocActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        

    }//GEN-LAST:event_uploaddocActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton uploaddoc;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
    private String filename;
    private String name;
}
